export const API_ENDPOINTS = {
  statistics: {
    overview: 'Statistics/Overview',
  },
  employers: {
    addLocation: 'Employers/AddLocation',
    addSupervisor: 'Employers/AddSupervisor',
    activate: 'Employers/Activate',
    ban: 'Employers/Ban',
    createWorkerPayout: 'Employers/CreateWorkerPayout',
    exportCommissionPoliciesCsv: 'Employers/ExportCommissionPoliciesCsv',
    getById: 'Employers/GetById',
    getCommissionReceivableByPeriod: 'Employers/GetCommissionReceivableByPeriod',
    getCommissionEstimate: 'Employers/GetCommissionEstimate',
    getCommissionPolicy: 'Employers/GetCommissionPolicy',
    list: 'Employers/List',
    listCommissionReceivables: 'Employers/ListCommissionReceivables',
    listCommissionSummaries: 'Employers/ListCommissionSummaries',
    failWorkerPayout: 'Employers/FailWorkerPayout',
    generateCommissionReceivable: 'Employers/GenerateCommissionReceivable',
    markWorkerPayoutAsProcessing: 'Employers/MarkWorkerPayoutAsProcessing',
    removeSupervisor: 'Employers/RemoveSupervisor',
    retryWorkerPayout: 'Employers/RetryWorkerPayout',
    setCommissionPolicy: 'Employers/SetCommissionPolicy',
    suspend: 'Employers/Suspend',
  },
  workers: {
    addSkill: 'Workers/AddSkill',
    liveStatus: 'Workers/LiveStatus',
    getSelfSummary: 'Workers/GetSelfSummary',
    getSelfFullDetail: 'Workers/GetSelfFullDetail',
    getDetail: 'Workers/GetDetail',
    getById: 'Workers/GetById',
    list: 'Workers/List',
  },
  systemUserGroups: {
    activate: 'SystemUserGroups/Activate',
    addPermission: 'SystemUserGroups/AddPermission',
    deactivate: 'SystemUserGroups/Deactivate',
    list: 'SystemUserGroups/List',
  },
  jobPostings: {
    cancel: 'JobPostings/Cancel',
    complete: 'JobPostings/Complete',
    create: 'JobPostings/Create',
    addSkill: 'JobPostings/AddSkill',
    listOpen: 'JobPostings/ListOpen',
    listSemanticMatched: 'JobPostings/ListSemanticMatched',
    listByEmployer: 'JobPostings/ListByEmployer',
    getById: 'JobPostings/GetById',
    publish: 'JobPostings/Publish',
    removeSkill: 'JobPostings/RemoveSkill',
    update: 'JobPostings/Update',
  },
  jobApplications: {
    accept: 'JobApplications/Accept',
    list: 'JobApplications/List',
    myApplications: 'JobApplications/MyApplications',
    reject: 'JobApplications/Reject',
    submit: 'JobApplications/Submit',
    withdraw: 'JobApplications/Withdraw',
  },
  shiftAssignments: {
    checkIn: 'ShiftAssignments/CheckIn',
    checkOut: 'ShiftAssignments/CheckOut',
    create: 'ShiftAssignments/Create',
    myAssignments: 'ShiftAssignments/MyAssignments',
    supervisorCheckIn: 'ShiftAssignments/SupervisorCheckIn',
  },
  systemUsers: {
    ban: 'SystemUsers/Ban',
    changePassword: 'SystemUsers/ChangePassword',
    list: 'SystemUsers/List',
    login: 'SystemUsers/Login',
    me: 'SystemUsers/Me',
    reactivate: 'SystemUsers/Reactivate',
    refreshToken: 'SystemUsers/RefreshToken',
    requestEmailVerification: 'SystemUsers/RequestEmailVerification',
    registerWorker: 'SystemUsers/RegisterWorker',
    registerEmployer: 'SystemUsers/RegisterEmployer',
    registerAdmin: 'SystemUsers/RegisterAdmin',
    suspend: 'SystemUsers/Suspend',
    verifyEmail: 'SystemUsers/VerifyEmail',
  },
} as const

export type ApiEndpoints = typeof API_ENDPOINTS
