export const API_ENDPOINTS = {
  statistics: {
    overview: 'Statistics/Overview',
  },
  employers: {
    activate: 'Employers/Activate',
    ban: 'Employers/Ban',
    getById: 'Employers/GetById',
    list: 'Employers/List',
    suspend: 'Employers/Suspend',
  },
  workers: {
    addSkill: 'Workers/AddSkill',
    getDetail: 'Workers/GetDetail',
    getById: 'Workers/GetById',
    list: 'Workers/List',
  },
  systemUserGroups: {
    activate: 'SystemUserGroups/Activate',
    addPermission: 'SystemUserGroups/AddPermission',
    deactivate: 'SystemUserGroups/Deactivate',
    list: 'SystemUserGroups/List',
  },
  jobPostings: {
    cancel: 'JobPostings/Cancel',
    complete: 'JobPostings/Complete',
    create: 'JobPostings/Create',
    addSkill: 'JobPostings/AddSkill',
    listOpen: 'JobPostings/ListOpen',
    listByEmployer: 'JobPostings/ListByEmployer',
    getById: 'JobPostings/GetById',
    publish: 'JobPostings/Publish',
    removeSkill: 'JobPostings/RemoveSkill',
    update: 'JobPostings/Update',
  },
  jobApplications: {
    accept: 'JobApplications/Accept',
    list: 'JobApplications/List',
    reject: 'JobApplications/Reject',
    submit: 'JobApplications/Submit',
    withdraw: 'JobApplications/Withdraw',
  },
  systemUsers: {
    ban: 'SystemUsers/Ban',
    changePassword: 'SystemUsers/ChangePassword',
    list: 'SystemUsers/List',
    login: 'SystemUsers/Login',
    me: 'SystemUsers/Me',
    reactivate: 'SystemUsers/Reactivate',
    refreshToken: 'SystemUsers/RefreshToken',
    requestEmailVerification: 'SystemUsers/RequestEmailVerification',
    registerWorker: 'SystemUsers/RegisterWorker',
    registerEmployer: 'SystemUsers/RegisterEmployer',
    registerAdmin: 'SystemUsers/RegisterAdmin',
    suspend: 'SystemUsers/Suspend',
    verifyEmail: 'SystemUsers/VerifyEmail',
  },
} as const

export type ApiEndpoints = typeof API_ENDPOINTS
