export const API_ENDPOINTS = {
  statistics: {
    overview: 'Statistics/Overview',
  },
  employers: {
    addLocation: 'Employers/AddLocation',
    addSupervisor: 'Employers/AddSupervisor',
    activate: 'Employers/Activate',
    ban: 'Employers/Ban',
    createWorkerPayout: 'Employers/CreateWorkerPayout',
    exportCommissionPoliciesCsv: 'Employers/ExportCommissionPoliciesCsv',
    getById: 'Employers/GetById',
    getCommissionReceivableByPeriod: 'Employers/GetCommissionReceivableByPeriod',
    getCommissionEstimate: 'Employers/GetCommissionEstimate',
    getCommissionPolicy: 'Employers/GetCommissionPolicy',
    list: 'Employers/List',
    listDisputes: 'Employers/ListDisputes',
    listLocations: 'Employers/ListLocations',
    listCommissionReceivables: 'Employers/ListCommissionReceivables',
    listCommissionSummaries: 'Employers/ListCommissionSummaries',
    listSupervisors: 'Employers/ListSupervisors',
    listWorkerPayouts: 'Employers/ListWorkerPayouts',
    failWorkerPayout: 'Employers/FailWorkerPayout',
    generateCommissionReceivable: 'Employers/GenerateCommissionReceivable',
    markWorkerPayoutAsProcessing: 'Employers/MarkWorkerPayoutAsProcessing',
    removeSupervisor: 'Employers/RemoveSupervisor',
    retryWorkerPayout: 'Employers/RetryWorkerPayout',
    setCommissionPolicy: 'Employers/SetCommissionPolicy',
    spotDashboardSummary: 'Employers/SpotDashboardSummary',
    suspend: 'Employers/Suspend',
    updateLocation: 'Employers/UpdateLocation',
    deleteLocation: 'Employers/DeleteLocation',
    workerPortfolio: 'Employers/WorkerPortfolio',
  },
  workers: {
    addAvailability: 'Workers/AddAvailability',
    addCertificate: 'Workers/AddCertificate',
    addEducation: 'Workers/AddEducation',
    addExperience: 'Workers/AddExperience',
    addReference: 'Workers/AddReference',
    addSkill: 'Workers/AddSkill',
    delete: 'Workers/Delete',
    liveStatus: 'Workers/LiveStatus',
    getSelfSummary: 'Workers/GetSelfSummary',
    getSelfFullDetail: 'Workers/GetSelfFullDetail',
    getDetail: 'Workers/GetDetail',
    getById: 'Workers/GetById',
    list: 'Workers/List',
    removeAvailability: 'Workers/RemoveAvailability',
    removeCertificate: 'Workers/RemoveCertificate',
    removeEducation: 'Workers/RemoveEducation',
    removeExperience: 'Workers/RemoveExperience',
    removeReference: 'Workers/RemoveReference',
    removeSkill: 'Workers/RemoveSkill',
    semanticSearch: 'Workers/SemanticSearch',
    updateProfile: 'Workers/UpdateProfile',
  },
  systemUserGroups: {
    activate: 'SystemUserGroups/Activate',
    addPermission: 'SystemUserGroups/AddPermission',
    deactivate: 'SystemUserGroups/Deactivate',
    list: 'SystemUserGroups/List',
  },
  jobPostings: {
    cancel: 'JobPostings/Cancel',
    complete: 'JobPostings/Complete',
    create: 'JobPostings/Create',
    addSkill: 'JobPostings/AddSkill',
    listOpen: 'JobPostings/ListOpen',
    listSemanticMatched: 'JobPostings/ListSemanticMatched',
    listByEmployer: 'JobPostings/ListByEmployer',
    getById: 'JobPostings/GetById',
    publish: 'JobPostings/Publish',
    removeSkill: 'JobPostings/RemoveSkill',
    update: 'JobPostings/Update',
  },
  jobApplications: {
    accept: 'JobApplications/Accept',
    list: 'JobApplications/List',
    myApplications: 'JobApplications/MyApplications',
    reject: 'JobApplications/Reject',
    submit: 'JobApplications/Submit',
    withdraw: 'JobApplications/Withdraw',
  },
  shiftAssignments: {
    checkIn: 'ShiftAssignments/CheckIn',
    checkOut: 'ShiftAssignments/CheckOut',
    create: 'ShiftAssignments/Create',
    listHistory: 'ShiftAssignments/ListHistory',
    myAssignments: 'ShiftAssignments/MyAssignments',
    supervisorCheckIn: 'ShiftAssignments/SupervisorCheckIn',
  },
  systemUsers: {
    ban: 'SystemUsers/Ban',
    changePassword: 'SystemUsers/ChangePassword',
    list: 'SystemUsers/List',
    login: 'SystemUsers/Login',
    me: 'SystemUsers/Me',
    myNotifications: 'SystemUsers/MyNotifications',
    markNotificationAsRead: 'SystemUsers/MarkNotificationAsRead',
    markAllNotificationsAsRead: 'SystemUsers/MarkAllNotificationsAsRead',
    reactivate: 'SystemUsers/Reactivate',
    refreshToken: 'SystemUsers/RefreshToken',
    requestEmailVerification: 'SystemUsers/RequestEmailVerification',
    registerWorker: 'SystemUsers/RegisterWorker',
    registerEmployer: 'SystemUsers/RegisterEmployer',
    registerAdmin: 'SystemUsers/RegisterAdmin',
    suspend: 'SystemUsers/Suspend',
    verifyEmail: 'SystemUsers/VerifyEmail',
  },
} as const

export type ApiEndpoints = typeof API_ENDPOINTS
